### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by ad3429** [kurleb10/prj-rev-bwfs-dasmoto#5]
**Summary Grade: Satisfactory**

Good job! Your files are organized nicely, and you did a great job of following the client specification -- this is an important skill to have as a developer and you seem to understand that. Moreover, you generally followed good code practice, so make sure to keep that up!

I have made some comments in your code to take note of. First off, make sure to comment the main parts of your code (both your HTML and CSS) in future projects. This will greatly help your development flow, especially as your projects get larger and more complex. Here is a quick refresher on commenting in HTML and CSS, respectively:

<img width="197" alt="html_comment" src="https://user-images.githubusercontent.com/25671399/33144181-260ecbbc-cf8a-11e7-8c11-9f3c7db1105c.png">

<img width="178" alt="css comment" src="https://user-images.githubusercontent.com/25671399/33144185-2766b2f4-cf8a-11e7-9869-14dfbc812733.png">

Next off, it seems you may have incorrectly linked to your CSS file and images by linking to ./resources, however your folder name has a capital R so it should be ./Resources. This should be a simple fix. 

Good job overall! As a further challenge, try using css to design your webpage even further! You did a great job in following the client specification, but for your own practice you should see how creative you can get by taking the design/styling of your site to the next level (for example, you can try experimenting with background colors on your other divs).

**Comment by kurleb10** [comment]
Thank you
